apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "{{ .Release.Name }}-http-frontend"
  labels:
    app: "http-frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "http-frontend"
  template:
    metadata:
      labels:
        app: "http-frontend"
    spec:
      containers:
        - name: "http-frontend"
          image: {{ .Values.images.httpFrontendImage | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.internal_port }}
          env:
            - name: "RABBITMQ_CONNECTION_HOST"
              value: {{ .Values.rabbitmq.service.clusterIP | quote }}
              # value: "http://{{ .Release.Name }}-rabbitmq-headless.{{ .Release.Namespace }}.svc.{{ .Values.rabbitmq.clusterDomain }}"
            - name: "RABBITMQ_CONNECTION_PORT"
              value: {{ .Values.rabbitmq.containerPorts.amqp | quote }}
            - name: "RABBITMQ_CONNECTION_USER"
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: "RABBITMQ_CONNECTION_PASS"
              value: {{ .Values.rabbitmq.auth.password | quote }}
            - name: "RABBITMQ_JOBS_QUEUE"
              value: {{ .Values.general_config.jobs_queue_name | quote }}
            - name: "REQUEST_TIMEOUT"
              value: {{ .Values.general_config.request_timeout | quote }}
            - name: "RUST_LOG"
              value: {{ .Values.general_config.log_level | quote }}
