apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: "http-frontend"
  ports:
    - port: {{ .Values.service.internal_port }}
      targetPort: {{ .Values.service.internal_port }}
      nodePort: {{ .Values.service.port }}
