images:
  llmImage: "ollama-qwen25-05b:latest"
  llmHandlerImage: "llm_handler:latest"
  httpFrontendImage: "http_frontend:latest"
  pullPolicy: IfNotPresent

autoscaling:
  fallbackReplicas: 4
  minReplicas: 1
  maxReplicas: 10
  messages_per_llm_pod: 1

general_config:
  log_level: INFO
  jobs_queue_name: "jobs-queue"
  request_timeout: 60

llms:
  host: "http://localhost:11434"
  model: "qwen2.5:0.5b"
  cpu_request: 1.5
  memory_request: 1G
  cpu_limit: 2 # Capped at 2 for the sake of making autoscaling useful in small deployments

service:
  type: NodePort
  port: 30434
  internal_port: 43196

rabbitmq:
  replicaCount: 3
  auth:
    username: "default-user"
    password: "eMs6lx9eoo0ntPob"
    securePassword: false
  service:
    type: "ClusterIP"
    clusterIP: "10.108.9.161"
  persistence:
    enabled: false

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}
